# Generated by Django 5.0.6 on 2024-05-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_drone_is_deleted_rental_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
